/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dolgame;

public class App {
    public static void getGreeting() {
        System.out.println("hello");
    }

    public static void main(String[] args) {
        getGreeting();


    }
}
