/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dolgame;

import java.sql.Connection;

public class App {
    public static void getGreeting() {
        System.out.println("hello");
    }

    public static void main(String[] args) {
        DBConnect.dbChecking();
        Connection connection = DBConnect.connection;
        getGreeting();
    }
}
